# Generated by Django 5.0.7 on 2024-08-26 16:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_uuid_review_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
